[project]
name = "HealthFlow"
version = "0.1.0"
description = "Self-Evolving LLM Agent for Healthcare with Experience Accumulation and Sensitive Data Protection"
readme = "README.md"
requires-python = ">=3.12"
keywords = ["healthcare", "ai", "llm", "agents", "self-evolving", "medical"]

dependencies = [
    # Core dependencies
    "openai>=1.0.0",
    "numpy>=1.21.0",
    "pandas>=1.3.0",
    "aiohttp>=3.8.0",
    "httpx>=0.24.0",
    "python-dotenv>=1.0.0",
    "tqdm>=4.64.0",
    "scipy>=1.7.0",
    # Testing
    "pytest>=6.0.0",
    "pytest-asyncio>=0.18.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0.0",
    "pytest-asyncio>=0.18.0",
    "pytest-cov>=3.0.0",
    "black>=22.0.0",
    "mypy>=0.910",
    "flake8>=4.0.0",
    "isort>=5.0.0",
    "pre-commit>=2.15.0",
]