[project]
name = "HealthFlow"
version = "0.1.0"
description = "Self-Evolving LLM Agent for Healthcare with Experience Accumulation and Tool Creation"
readme = "README.md"
requires-python = ">=3.12"
keywords = ["healthcare", "ai", "llm", "agents", "self-evolving", "medical"]

dependencies = [
    # Core LLM and AI dependencies
    "openai>=1.0.0",
    "anthropic>=0.25.0",
    "google-generativeai>=0.5.0",
    
    # Data processing and scientific computing
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "scipy>=1.10.0",
    "scikit-learn>=1.3.0",
    
    # Async and HTTP
    "aiohttp>=3.9.0",
    "httpx>=0.25.0",
    "asyncio>=3.11.0",
    
    # Configuration and utilities
    "python-dotenv>=1.0.0",
    "pydantic>=2.0.0",
    "typer>=0.9.0",
    "rich>=13.0.0",
    "tqdm>=4.66.0",
    
    # Data persistence
    "pyarrow>=13.0.0",
    "polars>=0.19.0",
    
    # Code execution and tools
    "jupyter-client>=8.0.0",
    "ipykernel>=6.25.0",
    "subprocess32>=3.5.0; python_version<'3.3'",
]

[project.scripts]
healthflow = "healthflow.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"