export type AppDemoStageId = 'memory' | 'planner' | 'executor' | 'evaluator' | 'reflector'

export type AppDemoArtifactKind = 'markdown' | 'json' | 'table' | 'chart' | 'log'

export type AppDemoTableValue = string | number

export interface AppDemoStage {
  id: AppDemoStageId
  label: string
  title: string
  status: 'completed'
  summary: string
  details: string[]
}

export interface AppDemoInputFile {
  name: string
  href: string
  rows: number
  columns: string[]
  description: string
}

export interface AppDemoTableArtifact {
  id: string
  label: string
  path: string
  kind: 'table'
  description: string
  columns: string[]
  rows: Record<string, AppDemoTableValue>[]
}

export interface AppDemoJsonArtifact {
  id: string
  label: string
  path: string
  kind: 'json'
  description: string
  value: Record<string, unknown>
}

export interface AppDemoMarkdownArtifact {
  id: string
  label: string
  path: string
  kind: 'markdown'
  description: string
  content: string
}

export interface AppDemoLogArtifact {
  id: string
  label: string
  path: string
  kind: 'log'
  description: string
  lines: string[]
}

export interface AppDemoChartPoint {
  x: number
  y: number
  label?: string
}

export interface AppDemoChartBar {
  label: string
  value: number
  count: number
}

export interface AppDemoChartArtifact {
  id: string
  label: string
  path: string
  kind: 'chart'
  description: string
  chart:
    | {
        type: 'line'
        title: string
        metric: string
        xLabel: string
        yLabel: string
        points: AppDemoChartPoint[]
      }
    | {
        type: 'bars'
        title: string
        metric: string
        xLabel: string
        yLabel: string
        bars: AppDemoChartBar[]
      }
}

export type AppDemoArtifact =
  | AppDemoTableArtifact
  | AppDemoJsonArtifact
  | AppDemoMarkdownArtifact
  | AppDemoLogArtifact
  | AppDemoChartArtifact

export interface AppDemoMetric {
  label: string
  value: string
  note: string
}

export interface AppDemoChatMessage {
  role: 'user' | 'assistant'
  label: string
  body: string
  attachments?: string[]
}

export const liveRuntimeUrl = 'https://healthflow-app.medx-pku.com'

export const appDemoTitle = 'ICU Mortality Risk Modeling'

export const appDemoDescription =
  'Reference ICU EHR workflow with a prepared input cohort, stage-by-stage trace, workspace deliverables, and final clinical summary.'

export const appDemoPrompt =
  'Use the attached ICU EHR cohort to produce a compact mortality risk diagnostic packet. Inspect the schema first, build a patient-level baseline model, generate calibration and ranking diagnostics, save the figures and tables into the workspace, and finish with a short clinical summary that references the artifacts.'

export const appDemoInputFile: AppDemoInputFile = {
  name: 'icu_mortality_cohort.csv',
  href: '/demo/icu_mortality_cohort.csv',
  rows: 18,
  columns: [
    'subject_id',
    'mortality',
    'label',
    'age',
    'sex',
    'event_time',
    'discharge_time',
    'heart_rate',
    'systolic_bp',
    'respiratory_rate',
    'temperature_c',
    'glucose',
    'los_days',
  ],
  description: 'Small ICU cohort used by the HealthFlow clinical example.',
}

export const appDemoMetrics: AppDemoMetric[] = [
  { label: 'Cohort', value: '18 admissions', note: 'Patient-level rows after schema inspection.' },
  { label: 'Outcome', value: '50.0%', note: 'In-hospital mortality prevalence in the fixture.' },
  { label: 'AUROC', value: '0.892', note: 'Ranking diagnostic generated by the baseline model.' },
  { label: 'AUPRC', value: '0.801', note: 'Precision-recall summary for the positive class.' },
]

export const appDemoStages: AppDemoStage[] = [
  {
    id: 'memory',
    label: 'Memory',
    title: 'Retrieved EHR modeling safeguards',
    status: 'completed',
    summary: 'Matched the request to predictive modeling and risk stratification workflows.',
    details: [
      'Confirmed the task family as EHR predictive modeling.',
      'Selected safeguards for prevalence checks and calibration evidence.',
      'Scoped reusable workflows to tabular modeling and clinical packet generation.',
    ],
  },
  {
    id: 'planner',
    label: 'Plan',
    title: 'Locked a patient-level risk packet plan',
    status: 'completed',
    summary: 'Defined schema checks, model training, artifact exports, and clinical reporting.',
    details: [
      'Inspect the cohort schema and confirm outcome prevalence.',
      'Train a reproducible patient-level baseline model.',
      'Render ROC, calibration, and risk distribution diagnostics.',
      'Summarize high-risk patient patterns and export deliverables.',
    ],
  },
  {
    id: 'executor',
    label: 'Execute',
    title: 'Generated figures, tables, and report artifacts',
    status: 'completed',
    summary: 'Produced a compact workspace with metrics, predictions, figures, vignettes, and final report.',
    details: [
      'Saved metrics and cohort profile as structured JSON.',
      'Saved predictions and feature importance as CSV tables.',
      'Rendered ROC, calibration, and risk distribution charts.',
    ],
  },
  {
    id: 'evaluator',
    label: 'Evaluate',
    title: 'Cleared the packet for clinical review',
    status: 'completed',
    summary: 'The generated workspace was coherent, clinically plausible, and presentation-ready.',
    details: [
      'Verified that key outputs align with the requested deliverables.',
      'Checked that ranking and calibration diagnostics are both present.',
      'Returned score 0.94 with no retry recommended.',
    ],
  },
  {
    id: 'reflector',
    label: 'Reflect',
    title: 'Captured reusable workflow guidance',
    status: 'completed',
    summary: 'Stored lessons about pairing diagnostics and grounding low-prevalence narratives.',
    details: [
      'Validated the prevalence-check safeguard.',
      'Recorded that ROC, calibration, and risk distribution should ship together.',
      'Recorded that cohort profiles and vignettes help ground the clinical narrative.',
    ],
  },
]

export const appDemoChatMessages: AppDemoChatMessage[] = [
  {
    role: 'user',
    label: 'User request',
    body: appDemoPrompt,
    attachments: [appDemoInputFile.name],
  },
  {
    role: 'assistant',
    label: 'HealthFlow result',
    body:
      'Built a compact ICU mortality packet for 18 admissions. The baseline model reached AUROC 0.892 with good rank ordering, and the highest-risk patients consistently combined older age, low systolic blood pressure, elevated lactate, and tachycardia. The workspace contains predictions, feature importance, cohort profile, vignettes, figures, and the final report.',
    attachments: ['figures/roc_curve.png', 'figures/calibration.png', 'figures/risk_distribution.png'],
  },
]

const metricsJson = {
  task: 'icu_mortality_prediction',
  cohort_size: 18,
  positive_cases: 9,
  outcome_prevalence: 0.5,
  auroc: 0.892,
  auprc: 0.801,
  brier_score: 0.123,
  sensitivity_at_0_5: 0.889,
  specificity_at_0_5: 0.867,
  top_risk_pattern:
    'Older patients with hypotension, tachycardia, and elevated lactate clustered in the highest-risk bucket.',
}

export const appDemoArtifacts: AppDemoArtifact[] = [
  {
    id: 'report',
    label: 'final_report.md',
    path: 'runtime/report.md',
    kind: 'markdown',
    description: 'Clinician-facing summary that references the generated workspace artifacts.',
    content:
      '# ICU Mortality Risk Report\n\n## Executive Summary\n\n- Cohort size: 18 admissions\n- Positive outcome count: 9\n- AUROC: 0.892\n- AUPRC: 0.801\n- Brier score: 0.123\n\n## Clinical Takeaways\n\nOlder patients with hypotension, tachycardia, and elevated lactate clustered in the highest-risk bucket.\n\n## Leading Predictors\n\n- **lactate** (0.28): Perfusion failure was the strongest nonlinear driver.\n- **systolic_bp** (0.21): Persistent hypotension sharply increased predicted risk.\n- **age** (0.17): Advanced age amplified every hemodynamic signal.\n- **glucose** (0.13): Stress hyperglycemia separated several high-risk patients.\n\n## Deliverables\n\n- `metrics.json`\n- `tables/predictions.csv`\n- `tables/feature_importance.csv`\n- `tables/cohort_profile.json`\n- `notes/patient_vignettes.md`\n- `figures/roc_curve.png`\n- `figures/calibration.png`\n- `figures/risk_distribution.png`',
  },
  {
    id: 'metrics',
    label: 'metrics.json',
    path: 'sandbox/metrics.json',
    kind: 'json',
    description: 'Model and cohort metrics generated by the demo run.',
    value: metricsJson,
  },
  {
    id: 'predictions',
    label: 'predictions.csv',
    path: 'sandbox/tables/predictions.csv',
    kind: 'table',
    description: 'Selected patient-level predictions sorted by risk.',
    columns: ['subject_id', 'mortality', 'age', 'sex', 'predicted_risk', 'risk_bucket'],
    rows: [
      { subject_id: '1015', mortality: 1, age: 86, sex: 'F', predicted_risk: 0.91, risk_bucket: 'critical' },
      { subject_id: '1004', mortality: 1, age: 83, sex: 'M', predicted_risk: 0.87, risk_bucket: 'critical' },
      { subject_id: '1007', mortality: 1, age: 76, sex: 'F', predicted_risk: 0.84, risk_bucket: 'critical' },
      { subject_id: '1012', mortality: 1, age: 81, sex: 'M', predicted_risk: 0.79, risk_bucket: 'critical' },
      { subject_id: '1017', mortality: 1, age: 78, sex: 'F', predicted_risk: 0.77, risk_bucket: 'critical' },
    ],
  },
  {
    id: 'feature-importance',
    label: 'feature_importance.csv',
    path: 'sandbox/tables/feature_importance.csv',
    kind: 'table',
    description: 'Top predictors and clinical interpretation notes.',
    columns: ['feature', 'importance', 'clinical_note'],
    rows: [
      { feature: 'lactate', importance: 0.28, clinical_note: 'Perfusion failure was the strongest driver.' },
      { feature: 'systolic_bp', importance: 0.21, clinical_note: 'Hypotension sharply increased predicted risk.' },
      { feature: 'age', importance: 0.17, clinical_note: 'Advanced age amplified hemodynamic signals.' },
      { feature: 'glucose', importance: 0.13, clinical_note: 'Stress hyperglycemia separated high-risk patients.' },
      { feature: 'respiratory_rate', importance: 0.12, clinical_note: 'Tachypnea remained important after adjustment.' },
    ],
  },
  {
    id: 'cohort-profile',
    label: 'cohort_profile.json',
    path: 'sandbox/tables/cohort_profile.json',
    kind: 'json',
    description: 'Compact cohort profile used by the final report.',
    value: {
      cohort_size: 18,
      female_count: 9,
      male_count: 9,
      median_age: 68,
      median_los_days: 4.0,
      high_risk_count: 5,
      critical_subject_ids: ['1015', '1004', '1007', '1012', '1017'],
    },
  },
  {
    id: 'vignettes',
    label: 'patient_vignettes.md',
    path: 'sandbox/notes/patient_vignettes.md',
    kind: 'markdown',
    description: 'Narrative review of the highest-risk patients.',
    content:
      '# Patient Vignettes\n\n## Subject 1015\n\n- Risk bucket: critical\n- Predicted risk: 0.910\n- Snapshot: age 86, SBP 87, HR 124, RR 29, lactate 3.4, glucose 226\n\n## Subject 1004\n\n- Risk bucket: critical\n- Predicted risk: 0.870\n- Snapshot: age 83, SBP 88, HR 118, RR 27, lactate 3.0, glucose 201\n\n## Subject 1007\n\n- Risk bucket: critical\n- Predicted risk: 0.840\n- Snapshot: age 76, SBP 92, HR 121, RR 28, lactate 3.2, glucose 214',
  },
  {
    id: 'roc',
    label: 'roc_curve.png',
    path: 'sandbox/figures/roc_curve.png',
    kind: 'chart',
    description: 'Ranking diagnostic for the mortality risk model.',
    chart: {
      type: 'line',
      title: 'ROC Curve',
      metric: 'AUROC 0.892',
      xLabel: 'False positive rate',
      yLabel: 'True positive rate',
      points: [
        { x: 0, y: 0 },
        { x: 0.05, y: 0.31 },
        { x: 0.12, y: 0.58 },
        { x: 0.24, y: 0.74 },
        { x: 0.4, y: 0.86 },
        { x: 0.68, y: 0.95 },
        { x: 1, y: 1 },
      ],
    },
  },
  {
    id: 'calibration',
    label: 'calibration.png',
    path: 'sandbox/figures/calibration.png',
    kind: 'chart',
    description: 'Calibration check used alongside ranking performance.',
    chart: {
      type: 'line',
      title: 'Calibration',
      metric: 'Brier 0.123',
      xLabel: 'Predicted risk',
      yLabel: 'Observed mortality',
      points: [
        { x: 0.1, y: 0.08 },
        { x: 0.28, y: 0.22 },
        { x: 0.48, y: 0.5 },
        { x: 0.68, y: 0.71 },
        { x: 0.86, y: 0.89 },
      ],
    },
  },
  {
    id: 'risk-distribution',
    label: 'risk_distribution.png',
    path: 'sandbox/figures/risk_distribution.png',
    kind: 'chart',
    description: 'Distribution of predicted risk buckets.',
    chart: {
      type: 'bars',
      title: 'Risk Distribution',
      metric: '5 critical cases',
      xLabel: 'Risk bucket',
      yLabel: 'Admissions',
      bars: [
        { label: 'Low', value: 8, count: 8 },
        { label: 'Elevated', value: 5, count: 5 },
        { label: 'Critical', value: 5, count: 5 },
      ],
    },
  },
  {
    id: 'logs',
    label: 'execution.log',
    path: 'runtime/events.jsonl',
    kind: 'log',
    description: 'Representative trace events from the HealthFlow run.',
    lines: [
      'memory retrieval_completed selected_count=2 status=completed',
      'planner plan_generated objective=Build an in-hospital mortality risk packet',
      'executor execution_completed artifact_count=9 return_code=0',
      'evaluator evaluation_completed score=0.94 status=success',
      'reflector memory_update action=validate experience_id=exp-showcase-icu-balance',
    ],
  },
]

export const coreAppDemoArtifactIds = [
  'report',
  'metrics',
  'predictions',
  'feature-importance',
  'roc',
  'calibration',
  'risk-distribution',
]

export const resolveAppDemoArtifact = (artifactId: string) =>
  appDemoArtifacts.find((artifact) => artifact.id === artifactId) ?? null
